import 'entities/rudiment.dart';

class RudimentCatalog {
  RudimentCatalog._();

  static const List<Rudiment> all = [
    Rudiment(
      id: 'single-stroke-roll',
      number: 1,
      name: 'Single Stroke Roll',
      category: 'Roll',
      shortDescription: 'Alternating strokes with a smooth and even pulse.',
    ),
    Rudiment(
      id: 'single-stroke-four',
      number: 2,
      name: 'Single Stroke Four',
      category: 'Roll',
      shortDescription: 'Four notes with alternating sticking.',
    ),
    Rudiment(
      id: 'single-stroke-seven',
      number: 3,
      name: 'Single Stroke Seven',
      category: 'Roll',
      shortDescription: 'Seven alternating notes for control and flow.',
    ),
    Rudiment(
      id: 'multiple-bounce-roll',
      number: 4,
      name: 'Multiple Bounce Roll',
      category: 'Roll',
      shortDescription: 'A buzz-style roll with controlled rebound.',
    ),
    Rudiment(
      id: 'triple-stroke-roll',
      number: 5,
      name: 'Triple Stroke Roll',
      category: 'Roll',
      shortDescription: 'Three strokes per hand with rebound control.',
    ),
    Rudiment(
      id: 'double-stroke-open-roll',
      number: 6,
      name: 'Double Stroke Open Roll',
      category: 'Roll',
      shortDescription: 'Clean alternating doubles with clear spacing.',
    ),
    Rudiment(
      id: 'five-stroke-roll',
      number: 7,
      name: 'Five Stroke Roll',
      category: 'Roll',
      shortDescription: 'Two doubles followed by an accent.',
    ),
    Rudiment(
      id: 'six-stroke-roll',
      number: 8,
      name: 'Six Stroke Roll',
      category: 'Roll',
      shortDescription: 'Accent, two doubles, finish with an accent.',
    ),
    Rudiment(
      id: 'seven-stroke-roll',
      number: 9,
      name: 'Seven Stroke Roll',
      category: 'Roll',
      shortDescription: 'Three doubles followed by an accent.',
    ),
    Rudiment(
      id: 'nine-stroke-roll',
      number: 10,
      name: 'Nine Stroke Roll',
      category: 'Roll',
      shortDescription: 'Four doubles followed by an accent.',
    ),
    Rudiment(
      id: 'ten-stroke-roll',
      number: 11,
      name: 'Ten Stroke Roll',
      category: 'Roll',
      shortDescription: 'Four doubles followed by two accents.',
    ),
    Rudiment(
      id: 'eleven-stroke-roll',
      number: 12,
      name: 'Eleven Stroke Roll',
      category: 'Roll',
      shortDescription: 'Five doubles followed by an accent.',
    ),
    Rudiment(
      id: 'thirteen-stroke-roll',
      number: 13,
      name: 'Thirteen Stroke Roll',
      category: 'Roll',
      shortDescription: 'Six doubles followed by an accent.',
    ),
    Rudiment(
      id: 'fifteen-stroke-roll',
      number: 14,
      name: 'Fifteen Stroke Roll',
      category: 'Roll',
      shortDescription: 'Seven doubles followed by an accent.',
    ),
    Rudiment(
      id: 'seventeen-stroke-roll',
      number: 15,
      name: 'Seventeen Stroke Roll',
      category: 'Roll',
      shortDescription: 'Eight doubles followed by an accent.',
    ),
    Rudiment(
      id: 'single-paradiddle',
      number: 16,
      name: 'Single Paradiddle',
      category: 'Diddle',
      shortDescription: 'A tap-tap-diddle pattern for hand control.',
    ),
    Rudiment(
      id: 'double-paradiddle',
      number: 17,
      name: 'Double Paradiddle',
      category: 'Diddle',
      shortDescription: 'A longer paradiddle phrase with more flow.',
    ),
    Rudiment(
      id: 'triple-paradiddle',
      number: 18,
      name: 'Triple Paradiddle',
      category: 'Diddle',
      shortDescription: 'Extended paradiddle movement and endurance.',
    ),
    Rudiment(
      id: 'single-paradiddle-diddle',
      number: 19,
      name: 'Single Paradiddle-Diddle',
      category: 'Diddle',
      shortDescription: 'Paradiddle with an added diddle at the end.',
    ),
    Rudiment(
      id: 'flam',
      number: 20,
      name: 'Flam',
      category: 'Flam',
      shortDescription: 'Grace note and primary note played together.',
    ),
    Rudiment(
      id: 'flam-accent',
      number: 21,
      name: 'Flam Accent',
      category: 'Flam',
      shortDescription: 'Three-note phrase starting with a flam.',
    ),
    Rudiment(
      id: 'flam-tap',
      number: 22,
      name: 'Flam Tap',
      category: 'Flam',
      shortDescription: 'Taps with a flam on the leading note.',
    ),
    Rudiment(
      id: 'flamacue',
      number: 23,
      name: 'Flamacue',
      category: 'Flam',
      shortDescription: 'Flam-based phrase with a crisp ending.',
    ),
    Rudiment(
      id: 'flam-paradiddle',
      number: 24,
      name: 'Flam Paradiddle',
      category: 'Flam',
      shortDescription: 'Paradiddle phrasing with flam accents.',
    ),
    Rudiment(
      id: 'single-flammed-mill',
      number: 25,
      name: 'Single Flammed Mill',
      category: 'Flam',
      shortDescription: 'A flowing flam-based mill pattern.',
    ),
    Rudiment(
      id: 'flam-paradiddle-diddle',
      number: 26,
      name: 'Flam Paradiddle-Diddle',
      category: 'Flam',
      shortDescription: 'Paradiddle-diddle phrase with flam articulation.',
    ),
    Rudiment(
      id: 'pataflafla',
      number: 27,
      name: 'Pataflafla',
      category: 'Swiss',
      shortDescription: 'Short Swiss-style accent pattern with flams.',
    ),
    Rudiment(
      id: 'swiss-army-triplet',
      number: 28,
      name: 'Swiss Army Triplet',
      category: 'Swiss',
      shortDescription: 'Triplet phrasing with flam lead-ins.',
    ),
    Rudiment(
      id: 'inverted-flam-tap',
      number: 29,
      name: 'Inverted Flam Tap',
      category: 'Flam',
      shortDescription: 'A reversed flam feel built around taps.',
    ),
    Rudiment(
      id: 'flam-drag',
      number: 30,
      name: 'Flam Drag',
      category: 'Hybrid',
      shortDescription: 'Combination of flam and drag phrasing.',
    ),
    Rudiment(
      id: 'drag',
      number: 31,
      name: 'Drag',
      category: 'Drag',
      shortDescription: 'A grace-based drag articulation.',
    ),
    Rudiment(
      id: 'single-drag-tap',
      number: 32,
      name: 'Single Drag Tap',
      category: 'Drag',
      shortDescription: 'Drag leading into a single tap.',
    ),
    Rudiment(
      id: 'double-drag-tap',
      number: 33,
      name: 'Double Drag Tap',
      category: 'Drag',
      shortDescription: 'Drag leading into two taps.',
    ),
    Rudiment(
      id: 'lesson-25',
      number: 34,
      name: 'Lesson 25',
      category: 'Classic',
      shortDescription: 'A historic lesson pattern from rudimental study.',
    ),
    Rudiment(
      id: 'single-ratamacue',
      number: 35,
      name: 'Single Ratamacue',
      category: 'Drag',
      shortDescription: 'Drag-based phrase with a clean accent release.',
    ),
    Rudiment(
      id: 'double-ratamacue',
      number: 36,
      name: 'Double Ratamacue',
      category: 'Drag',
      shortDescription: 'Expanded ratamacue phrasing with more bounce.',
    ),
    Rudiment(
      id: 'triple-ratamacue',
      number: 37,
      name: 'Triple Ratamacue',
      category: 'Drag',
      shortDescription: 'Longest ratamacue form in the standard set.',
    ),
    Rudiment(
      id: 'drag-paradiddle-one',
      number: 38,
      name: 'Drag Paradiddle #1',
      category: 'Drag',
      shortDescription: 'Drag and paradiddle combination, first variation.',
    ),
    Rudiment(
      id: 'drag-paradiddle-two',
      number: 39,
      name: 'Drag Paradiddle #2',
      category: 'Drag',
      shortDescription: 'Drag and paradiddle combination, second variation.',
    ),
    Rudiment(
      id: 'single-dragadiddle',
      number: 40,
      name: 'Single Dragadiddle',
      category: 'Drag',
      shortDescription: 'Drag with paradiddle-like motion and flow.',
    ),
  ];
}
