import 'entities/rudiment.dart';

class RudimentCatalog {
  RudimentCatalog._();

  static const List<Rudiment> all = [
    Rudiment(number: 1, name: 'Single Stroke Roll', category: 'Roll'),
    Rudiment(number: 2, name: 'Single Stroke Four', category: 'Roll'),
    Rudiment(number: 3, name: 'Single Stroke Seven', category: 'Roll'),
    Rudiment(number: 4, name: 'Multiple Bounce Roll', category: 'Roll'),
    Rudiment(number: 5, name: 'Triple Stroke Roll', category: 'Roll'),
    Rudiment(number: 6, name: 'Double Stroke Open Roll', category: 'Roll'),
    Rudiment(number: 7, name: 'Five Stroke Roll', category: 'Roll'),
    Rudiment(number: 8, name: 'Six Stroke Roll', category: 'Roll'),
    Rudiment(number: 9, name: 'Seven Stroke Roll', category: 'Roll'),
    Rudiment(number: 10, name: 'Nine Stroke Roll', category: 'Roll'),
    Rudiment(number: 11, name: 'Ten Stroke Roll', category: 'Roll'),
    Rudiment(number: 12, name: 'Eleven Stroke Roll', category: 'Roll'),
    Rudiment(number: 13, name: 'Thirteen Stroke Roll', category: 'Roll'),
    Rudiment(number: 14, name: 'Fifteen Stroke Roll', category: 'Roll'),
    Rudiment(number: 15, name: 'Seventeen Stroke Roll', category: 'Roll'),
    Rudiment(number: 16, name: 'Single Paradiddle', category: 'Diddle'),
    Rudiment(number: 17, name: 'Double Paradiddle', category: 'Diddle'),
    Rudiment(number: 18, name: 'Triple Paradiddle', category: 'Diddle'),
    Rudiment(number: 19, name: 'Single Paradiddle-Diddle', category: 'Diddle'),
    Rudiment(number: 20, name: 'Flam', category: 'Flam'),
    Rudiment(number: 21, name: 'Flam Accent', category: 'Flam'),
    Rudiment(number: 22, name: 'Flam Tap', category: 'Flam'),
    Rudiment(number: 23, name: 'Flamacue', category: 'Flam'),
    Rudiment(number: 24, name: 'Flam Paradiddle', category: 'Flam'),
    Rudiment(number: 25, name: 'Single Flammed Mill', category: 'Flam'),
    Rudiment(number: 26, name: 'Flam Paradiddle-Diddle', category: 'Flam'),
    Rudiment(number: 27, name: 'Pataflafla', category: 'Swiss'),
    Rudiment(number: 28, name: 'Swiss Army Triplet', category: 'Swiss'),
    Rudiment(number: 29, name: 'Inverted Flam Tap', category: 'Flam'),
    Rudiment(number: 30, name: 'Flam Drag', category: 'Hybrid'),
    Rudiment(number: 31, name: 'Drag', category: 'Drag'),
    Rudiment(number: 32, name: 'Single Drag Tap', category: 'Drag'),
    Rudiment(number: 33, name: 'Double Drag Tap', category: 'Drag'),
    Rudiment(number: 34, name: 'Lesson 25', category: 'Classic'),
    Rudiment(number: 35, name: 'Single Ratamacue', category: 'Drag'),
    Rudiment(number: 36, name: 'Double Ratamacue', category: 'Drag'),
    Rudiment(number: 37, name: 'Triple Ratamacue', category: 'Drag'),
    Rudiment(number: 38, name: 'Drag Paradiddle #1', category: 'Drag'),
    Rudiment(number: 39, name: 'Drag Paradiddle #2', category: 'Drag'),
    Rudiment(number: 40, name: 'Single Dragadiddle', category: 'Drag'),
  ];
}
