import 'entities/rudiment.dart';

class RudimentCatalog {
  RudimentCatalog._();

  static const List<Rudiment> all = [
    Rudiment(
      number: 1,
      name: 'Single Stroke Roll',
      description: 'Toques simples alternados entre as mãos.',
      category: 'Roll',
    ),
    Rudiment(
      number: 2,
      name: 'Single Stroke Four',
      description: 'Grupo de quatro toques simples alternados.',
      category: 'Roll',
    ),
    Rudiment(
      number: 3,
      name: 'Single Stroke Seven',
      description: 'Grupo de sete toques simples alternados.',
      category: 'Roll',
    ),
    Rudiment(
      number: 4,
      name: 'Multiple Bounce Roll',
      description: 'Rulo utilizando múltiplos rebotes controlados.',
      category: 'Roll',
    ),
    Rudiment(
      number: 5,
      name: 'Triple Stroke Roll',
      description: 'Três toques consecutivos por mão.',
      category: 'Roll',
    ),
    Rudiment(
      number: 6,
      name: 'Double Stroke Open Roll',
      description: 'Rulo aberto de dois toques por mão.',
      category: 'Roll',
    ),
    Rudiment(
      number: 7,
      name: 'Five Stroke Roll',
      description: 'Rulo de cinco toques com acento final.',
      category: 'Roll',
    ),
    Rudiment(
      number: 8,
      name: 'Six Stroke Roll',
      description: 'Rulo de seis toques muito usado em viradas.',
      category: 'Roll',
    ),
    Rudiment(
      number: 9,
      name: 'Seven Stroke Roll',
      description: 'Rulo de sete toques com acento final.',
      category: 'Roll',
    ),
    Rudiment(
      number: 10,
      name: 'Nine Stroke Roll',
      description: 'Rulo de nove toques para desenvolver controle e resistência.',
      category: 'Roll',
    ),
    Rudiment(
      number: 11,
      name: 'Ten Stroke Roll',
      description: 'Rulo de dez toques com fechamento acentuado.',
      category: 'Roll',
    ),
    Rudiment(
      number: 12,
      name: 'Eleven Stroke Roll',
      description: 'Rulo de onze toques com cinco doubles.',
      category: 'Roll',
    ),
    Rudiment(
      number: 13,
      name: 'Thirteen Stroke Roll',
      description: 'Rulo de treze toques para resistência e uniformidade.',
      category: 'Roll',
    ),
    Rudiment(
      number: 14,
      name: 'Fifteen Stroke Roll',
      description: 'Rulo de quinze toques com sete doubles.',
      category: 'Roll',
    ),
    Rudiment(
      number: 15,
      name: 'Seventeen Stroke Roll',
      description: 'Rulo de dezessete toques exigindo resistência e controle.',
      category: 'Roll',
    ),
    Rudiment(
      number: 16,
      name: 'Single Paradiddle',
      description: 'Paradiddle básico para desenvolver coordenação e acentuação.',
      category: 'Diddle',
    ),
    Rudiment(
      number: 17,
      name: 'Double Paradiddle',
      description: 'Paradiddle estendido com duas sequências de simples.',
      category: 'Diddle',
    ),
    Rudiment(
      number: 18,
      name: 'Triple Paradiddle',
      description: 'Paradiddle em três grupos antes do double final.',
      category: 'Diddle',
    ),
    Rudiment(
      number: 19,
      name: 'Single Paradiddle-Diddle',
      description: 'Combinação de paradiddle com doubles.',
      category: 'Diddle',
    ),
    Rudiment(
      number: 20,
      name: 'Flam',
      description: 'Nota de apoio seguida do ataque principal.',
      category: 'Flam',
    ),
    Rudiment(
      number: 21,
      name: 'Flam Accent',
      description: 'Flam seguido por dois toques simples.',
      category: 'Flam',
    ),
    Rudiment(
      number: 22,
      name: 'Flam Tap',
      description: 'Alternância entre flam e tap.',
      category: 'Flam',
    ),
    Rudiment(
      number: 23,
      name: 'Flamacue',
      description: 'Combinação de flam, taps e acento final.',
      category: 'Flam',
    ),
    Rudiment(
      number: 24,
      name: 'Flam Paradiddle',
      description: 'Paradiddle iniciado com flam.',
      category: 'Flam',
    ),
    Rudiment(
      number: 25,
      name: 'Single Flammed Mill',
      description: 'Variação do mill utilizando flams.',
      category: 'Flam',
    ),
    Rudiment(
      number: 26,
      name: 'Flam Paradiddle-Diddle',
      description: 'Paradiddle-diddle iniciado com flam.',
      category: 'Flam',
    ),
    Rudiment(
      number: 27,
      name: 'Pataflafla',
      description: 'Sequência contínua de flams alternados.',
      category: 'Flam',
    ),
    Rudiment(
      number: 28,
      name: 'Swiss Army Triplet',
      description: 'Rudimento suíço baseado em tercinas.',
      category: 'Swiss',
    ),
    Rudiment(
      number: 29,
      name: 'Inverted Flam Tap',
      description: 'Variação invertida do Flam Tap.',
      category: 'Flam',
    ),
    Rudiment(
      number: 30,
      name: 'Flam Drag',
      description: 'Combinação de flam e drag.',
      category: 'Hybrid',
    ),
    Rudiment(
      number: 31,
      name: 'Drag',
      description: 'Grace notes seguidas de um ataque principal.',
      category: 'Drag',
    ),
    Rudiment(
      number: 32,
      name: 'Single Drag Tap',
      description: 'Drag seguido de um tap.',
      category: 'Drag',
    ),
    Rudiment(
      number: 33,
      name: 'Double Drag Tap',
      description: 'Dois drags antes do tap.',
      category: 'Drag',
    ),
    Rudiment(
      number: 34,
      name: 'Lesson 25',
      description: 'Rudimento clássico baseado em drags.',
      category: 'Classic',
    ),
    Rudiment(
      number: 35,
      name: 'Single Ratamacue',
      description: 'Ratamacue básico com um drag.',
      category: 'Drag',
    ),
    Rudiment(
      number: 36,
      name: 'Double Ratamacue',
      description: 'Ratamacue com dois drags.',
      category: 'Drag',
    ),
    Rudiment(
      number: 37,
      name: 'Triple Ratamacue',
      description: 'Ratamacue com três drags.',
      category: 'Drag',
    ),
    Rudiment(
      number: 38,
      name: 'Drag Paradiddle #1',
      description: 'Primeira variação do Drag Paradiddle.',
      category: 'Drag',
    ),
    Rudiment(
      number: 39,
      name: 'Drag Paradiddle #2',
      description: 'Segunda variação do Drag Paradiddle.',
      category: 'Drag',
    ),
    Rudiment(
      number: 40,
      name: 'Single Dragadiddle',
      description: 'Combinação de drag com paradiddle.',
      category: 'Drag',
    ),
  ];
}